spring:
  datasource:
    url: 
    username:
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  messages:
    basename: messages
  mail:
    host: 
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  sql:
    init:
      encoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    properties:
  # show_sql: true
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates
    suffix: .html

# org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
file:
  dir: C:\Users\ParkWonkyoung\Desktop\projects\files\



