spring:
  datasource:
    url:
    username: 
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  messages:
    basename: messages
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: truea
            required: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  sql:
    init:
      encoding=UTF-8
  jpa:
    hibernate:
      default_batch_fetch_size: 1000
      ddl-auto: update
    properties:
      hibernate:
      # show_sql: true
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates
    suffix: .html

# org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
file:
  dir: C:\Users\ParkWonkyoung\Desktop\projects\files\
  #이미지 경로저장
itemImgLocation: C:/projects/item/
  #프로젝트 내부가 아닌 자신의 컴퓨터에서 파일을 찾는 경로
uploadPath: file:///C:/projects/



